name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-python
        with:
           python-version: "3.10"
      - name: Flask
        run: python -m pip install flask
      - name: test
        run: python test.py
      #pip install -r requiments.txt